Use React Query instead of Redux
cloudogu/smeagol pull request #101
Opened 2021-02-22 12:43 UTC by mbehlendorf

### Changed
* Use React Query instead of Redux to manage server-state #100

2021-02-23 12:08 UTC, sdorra requested changes
Functionally the change looks good, but there are some things we should discuss.

This change contains a lot of mixed styles:

* Single Quotes vs Double Quotes
* Line end with semicolon and without
* Function definition with function keywork and as const
* isError vs error

We should consider using some tooling to force a consistent style. Eslint and prettier for example.

The other thing is the complete lack of types, even if we do not switch to typescript we should define types as much as we can. Each type helps the next developer to reach his goal faster and safer.

There is also a package-lock.json and a yarn.lock i’m not sure if the project uses npm or yarn.

2021-02-24 12:17 UTC, mbehlendorf commented on src/main/js/App.js
> +const queryClient = new QueryClient({defaultOptions: {queries: {retry: 0}}})
done

2021-02-24 12:18 UTC, mbehlendorf commented on src/main/js/App.js
>  class App extends Component {
done

2021-02-24 14:02 UTC, mbehlendorf commented on src/main/js/repository/modules/repositories.js
> +export function useRepositories() {
done

2021-02-24 14:02 UTC, mbehlendorf commented on src/main/js/repository/modules/repository.js
> +export function useRepository(id: string) {
done

2021-02-24 14:03 UTC, mbehlendorf commented on src/main/js/wiki/components/PageViewer.js
> +    onRestore: any,
done

2021-02-24 14:03 UTC, mbehlendorf commented on src/main/js/wiki/containers/Directory.js
> +    location: any
done

2021-02-24 14:03 UTC, mbehlendorf commented on src/main/js/wiki/containers/Directory.js
> +    const {isLoading, error, data} = useDirectory(repository, branch, path)
done

2021-02-24 14:03 UTC, mbehlendorf commented on src/main/js/wiki/containers/History.js
> +    location: any
done

2021-02-24 14:08 UTC, mbehlendorf commented on src/main/js/wiki/containers/Page.js
> +    const {repository, branch} = props.match.params;
done

2021-02-24 14:08 UTC, mbehlendorf commented on src/main/js/wiki/containers/Page.js
> +    const restorePageMutation = useRestorePage(repository, branch, path,  pushPageStateClosure())
done

2021-02-24 14:10 UTC, mbehlendorf commented on src/main/js/wiki/containers/Page.js
> +    wiki.branch = branch;
done

2021-02-24 14:10 UTC, mbehlendorf commented on src/main/js/wiki/containers/Search.js
> +    location: any
done

2021-02-24 14:11 UTC, mbehlendorf commented on src/main/js/wiki/containers/Search.js
> +    let search = (query: string) => {
done

2021-02-24 14:11 UTC, mbehlendorf commented on src/main/js/wiki/containers/Search.js
> +    const wikiQuery = useWiki(repository, branch)
done

2021-02-24 14:11 UTC, mbehlendorf commented on src/main/js/wiki/modules/directory.js
> +export function useDirectory(repository: string,branch:string,path:string) {
done

2021-02-24 14:12 UTC, mbehlendorf commented on src/main/js/wiki/modules/page.js
>  //@flow
done

2021-02-24 14:12 UTC, mbehlendorf commented on src/main/js/wiki/modules/pagehistory.js
>  // @flow
done

2021-02-24 14:13 UTC, mbehlendorf commented on src/main/js/wiki/modules/search.js
>  import {apiClient} from "../../apiclient";
done

2021-02-24 14:13 UTC, mbehlendorf commented on src/main/js/wiki/modules/wiki.js
>  //@flow
done

2021-02-24 16:58 UTC, mbehlendorf commented on src/main/js/wiki/containers/Page.js
>      };
done

2021-02-25 06:49 UTC, sdorra requested changes

2021-02-25 06:49 UTC, sdorra commented on package.json
> +    "@types/react-router": "^5.1.11",
The version of the types package should match the one from the dependencies.

2021-03-02 12:29 UTC, merged